
using System.Runtime.InteropServices;

public unsafe partial class TheSpredsheetEdmundHates
{
    // ============================================================
    // GENERATED BY IDA PERF HOOK GENERATOR
    // ============================================================

    // Function RVAs

    private const nuint simpleMusicPlayerRva = 0xA1BDF0;
    private const nuint globalProgressionDataRva = 0x35BD0;
    private const nuint mewDirectorRva = 0x35BD0;
    private const nuint mewsicControllerRva = 0x23FC90;
    private const nuint spawnDatabaseRva = 0x7AA9B0;
    private const nuint audioListenerRva = 0x95B030;
    private const nuint gameBaseRva = 0x7556D0;
    private const nuint houseDrawerUIRva = 0x2033A0;
    private const nuint ragdollRva = 0xDBF50;
    private const nuint furnitureBuildingUIRva = 0x1A5DE0;
    private const nuint furnitureClickHandlerRva = 0x1A0880;
    private const nuint butchBoxRva = 0xAE9D0;
    private const nuint catStatsDrawerRva = 0xEB170;
    private const nuint furnitureGridRva = 0x2E9DA0;
    private const nuint furniturePieceRva = 0x2ED8E0;
    private const nuint houseRva = 0x1E5D60;
    private const nuint houseCatRva = 0x1FD8B0;
    private const nuint houseCatClickManagerRva = 0x1FE940;
    private const nuint houseCatPhysicsRva = 0x1FF3F0;
    private const nuint housePipeRva = 0x208BE0;
    private const nuint houseTutorialDriverRva = 0x2095E0;
    private const nuint inventoryTrashDrawersRva = 0x35BD0;
    private const nuint nPCMapDrawerRva = 0x277A30;
    private const nuint singingCatRva = 0x79D990;
    private const nuint buttonRva = 0x97E2D0;
    private const nuint abilityTooltipRva = 0x5B2F0;
    private const nuint aABBTreeBroadphaseRva = 0xA03420;
    private const nuint audioSourceRva = 0x95BB50;
    private const nuint animationAudioEventsRva = 0x6A9C0;
    private const nuint catRagdollRva = 0xDCE70;
    private const nuint combatCatVoice_EmotionsRva = 0xEFF60;
    private const nuint furnitureGridIconsRva = 0x1A8120;
    private const nuint furnitureMenuButtonRva = 0x1A2A20;
    private const nuint houseDrawerPanelRva = 0x204320;
    private const nuint houseTestRva = 0x335AE0;
    private const nuint trashScreenItemBox2Rva = 0x213AC0;
    private const nuint buttonManagerRva = 0x980100;

    // Original / next-hook function pointers

    private static delegate* unmanaged<nint, void> _simpleMusicPlayerOriginal;
    private static delegate* unmanaged<void> _globalProgressionDataOriginal;
    private static delegate* unmanaged<void> _mewDirectorOriginal;
    private static delegate* unmanaged<nint, void> _mewsicControllerOriginal;
    private static delegate* unmanaged<nint, void> _spawnDatabaseOriginal;
    private static delegate* unmanaged<nint, void> _audioListenerOriginal;
    private static delegate* unmanaged<nint, void> _gameBaseOriginal;
    private static delegate* unmanaged<nint, void> _houseDrawerUIOriginal;
    private static delegate* unmanaged<nint, void> _ragdollOriginal;
    private static delegate* unmanaged<nint, void> _furnitureBuildingUIOriginal;
    private static delegate* unmanaged<nint, void> _furnitureClickHandlerOriginal;
    private static delegate* unmanaged<nint, void> _butchBoxOriginal;
    private static delegate* unmanaged<nint, void> _catStatsDrawerOriginal;
    private static delegate* unmanaged<nint, void> _furnitureGridOriginal;
    private static delegate* unmanaged<nint, void> _furniturePieceOriginal;
    private static delegate* unmanaged<nint, void> _houseOriginal;
    private static delegate* unmanaged<nint, void> _houseCatOriginal;
    private static delegate* unmanaged<nint, void> _houseCatClickManagerOriginal;
    private static delegate* unmanaged<nint, void> _houseCatPhysicsOriginal;
    private static delegate* unmanaged<nint, void> _housePipeOriginal;
    private static delegate* unmanaged<nint, void> _houseTutorialDriverOriginal;
    private static delegate* unmanaged<void> _inventoryTrashDrawersOriginal;
    private static delegate* unmanaged<nint, void> _nPCMapDrawerOriginal;
    private static delegate* unmanaged<nint, void> _singingCatOriginal;
    private static delegate* unmanaged<nint, void> _buttonOriginal;
    private static delegate* unmanaged<nint, void> _abilityTooltipOriginal;
    private static delegate* unmanaged<nint, void> _aABBTreeBroadphaseOriginal;
    private static delegate* unmanaged<nint, void> _audioSourceOriginal;
    private static delegate* unmanaged<nint, void> _animationAudioEventsOriginal;
    private static delegate* unmanaged<nint, void> _catRagdollOriginal;
    private static delegate* unmanaged<nint, void> _combatCatVoice_EmotionsOriginal;
    private static delegate* unmanaged<nint, void> _furnitureGridIconsOriginal;
    private static delegate* unmanaged<nint, void> _furnitureMenuButtonOriginal;
    private static delegate* unmanaged<nint, void> _houseDrawerPanelOriginal;
    private static delegate* unmanaged<nint, void> _houseTestOriginal;
    private static delegate* unmanaged<nint, void> _trashScreenItemBox2Original;
    private static delegate* unmanaged<nint, void> _buttonManagerOriginal;

    internal unsafe static void PerfInit()
    {
        _simpleMusicPlayerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)simpleMusicPlayerRva,
                    (delegate* unmanaged<nint, void>)&SimpleMusicPlayerHook
                );

        _globalProgressionDataOriginal =
            (delegate* unmanaged<void>)
                MewjectorApi.InstallHook(
                    (long)globalProgressionDataRva,
                    (delegate* unmanaged<void>)&GlobalProgressionDataHook
                );

        _mewDirectorOriginal =
            (delegate* unmanaged<void>)
                MewjectorApi.InstallHook(
                    (long)mewDirectorRva,
                    (delegate* unmanaged<void>)&MewDirectorHook
                );

        _mewsicControllerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)mewsicControllerRva,
                    (delegate* unmanaged<nint, void>)&MewsicControllerHook
                );

        _spawnDatabaseOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)spawnDatabaseRva,
                    (delegate* unmanaged<nint, void>)&SpawnDatabaseHook
                );

        _audioListenerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)audioListenerRva,
                    (delegate* unmanaged<nint, void>)&AudioListenerHook
                );

        _gameBaseOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)gameBaseRva,
                    (delegate* unmanaged<nint, void>)&GameBaseHook
                );

        _houseDrawerUIOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseDrawerUIRva,
                    (delegate* unmanaged<nint, void>)&HouseDrawerUIHook
                );

        _ragdollOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)ragdollRva,
                    (delegate* unmanaged<nint, void>)&RagdollHook
                );

        _furnitureBuildingUIOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furnitureBuildingUIRva,
                    (delegate* unmanaged<nint, void>)&FurnitureBuildingUIHook
                );

        _furnitureClickHandlerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furnitureClickHandlerRva,
                    (delegate* unmanaged<nint, void>)&FurnitureClickHandlerHook
                );

        _butchBoxOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)butchBoxRva,
                    (delegate* unmanaged<nint, void>)&ButchBoxHook
                );

        _catStatsDrawerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)catStatsDrawerRva,
                    (delegate* unmanaged<nint, void>)&CatStatsDrawerHook
                );

        _furnitureGridOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furnitureGridRva,
                    (delegate* unmanaged<nint, void>)&FurnitureGridHook
                );

        _furniturePieceOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furniturePieceRva,
                    (delegate* unmanaged<nint, void>)&FurniturePieceHook
                );

        _houseOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseRva,
                    (delegate* unmanaged<nint, void>)&HouseHook
                );

        _houseCatOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseCatRva,
                    (delegate* unmanaged<nint, void>)&HouseCatHook
                );

        _houseCatClickManagerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseCatClickManagerRva,
                    (delegate* unmanaged<nint, void>)&HouseCatClickManagerHook
                );

        _houseCatPhysicsOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseCatPhysicsRva,
                    (delegate* unmanaged<nint, void>)&HouseCatPhysicsHook
                );

        _housePipeOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)housePipeRva,
                    (delegate* unmanaged<nint, void>)&HousePipeHook
                );

        _houseTutorialDriverOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseTutorialDriverRva,
                    (delegate* unmanaged<nint, void>)&HouseTutorialDriverHook
                );

        _inventoryTrashDrawersOriginal =
            (delegate* unmanaged<void>)
                MewjectorApi.InstallHook(
                    (long)inventoryTrashDrawersRva,
                    (delegate* unmanaged<void>)&InventoryTrashDrawersHook
                );

        _nPCMapDrawerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)nPCMapDrawerRva,
                    (delegate* unmanaged<nint, void>)&NPCMapDrawerHook
                );

        _singingCatOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)singingCatRva,
                    (delegate* unmanaged<nint, void>)&SingingCatHook
                );

        _buttonOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)buttonRva,
                    (delegate* unmanaged<nint, void>)&ButtonHook
                );

        _abilityTooltipOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)abilityTooltipRva,
                    (delegate* unmanaged<nint, void>)&AbilityTooltipHook
                );

        _aABBTreeBroadphaseOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)aABBTreeBroadphaseRva,
                    (delegate* unmanaged<nint, void>)&AABBTreeBroadphaseHook
                );

        _audioSourceOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)audioSourceRva,
                    (delegate* unmanaged<nint, void>)&AudioSourceHook
                );

        _animationAudioEventsOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)animationAudioEventsRva,
                    (delegate* unmanaged<nint, void>)&AnimationAudioEventsHook
                );

        _catRagdollOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)catRagdollRva,
                    (delegate* unmanaged<nint, void>)&CatRagdollHook
                );

        _combatCatVoice_EmotionsOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)combatCatVoice_EmotionsRva,
                    (delegate* unmanaged<nint, void>)&CombatCatVoice_EmotionsHook
                );

        _furnitureGridIconsOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furnitureGridIconsRva,
                    (delegate* unmanaged<nint, void>)&FurnitureGridIconsHook
                );

        _furnitureMenuButtonOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)furnitureMenuButtonRva,
                    (delegate* unmanaged<nint, void>)&FurnitureMenuButtonHook
                );

        _houseDrawerPanelOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseDrawerPanelRva,
                    (delegate* unmanaged<nint, void>)&HouseDrawerPanelHook
                );

        _houseTestOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)houseTestRva,
                    (delegate* unmanaged<nint, void>)&HouseTestHook
                );

        _trashScreenItemBox2Original =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)trashScreenItemBox2Rva,
                    (delegate* unmanaged<nint, void>)&TrashScreenItemBox2Hook
                );

        _buttonManagerOriginal =
            (delegate* unmanaged<nint, void>)
                MewjectorApi.InstallHook(
                    (long)buttonManagerRva,
                    (delegate* unmanaged<nint, void>)&ButtonManagerHook
                );
    }

    [UnmanagedCallersOnly]
    private static void SimpleMusicPlayerHook(nint a1)
    {
        StartPerfLog("SimpleMusicPlayer");
        _simpleMusicPlayerOriginal(a1);
        EndPerfLog("SimpleMusicPlayer");
    }

    [UnmanagedCallersOnly]
    private static void GlobalProgressionDataHook()
    {
        StartPerfLog("GlobalProgressionData");
        _globalProgressionDataOriginal();
        EndPerfLog("GlobalProgressionData");
    }

    [UnmanagedCallersOnly]
    private static void MewDirectorHook()
    {
        StartPerfLog("MewDirector");
        _mewDirectorOriginal();
        EndPerfLog("MewDirector");
    }

    [UnmanagedCallersOnly]
    private static void MewsicControllerHook(nint a1)
    {
        StartPerfLog("MewsicController");
        _mewsicControllerOriginal(a1);
        EndPerfLog("MewsicController");
    }

    [UnmanagedCallersOnly]
    private static void SpawnDatabaseHook(nint a1)
    {
        StartPerfLog("SpawnDatabase");
        _spawnDatabaseOriginal(a1);
        EndPerfLog("SpawnDatabase");
    }

    [UnmanagedCallersOnly]
    private static void AudioListenerHook(nint a1)
    {
        StartPerfLog("AudioListener");
        _audioListenerOriginal(a1);
        EndPerfLog("AudioListener");
    }

    [UnmanagedCallersOnly]
    private static void GameBaseHook(nint a1)
    {
        StartPerfLog("GameBase");
        _gameBaseOriginal(a1);
        EndPerfLog("GameBase");
    }

    [UnmanagedCallersOnly]
    private static void HouseDrawerUIHook(nint a1)
    {
        StartPerfLog("HouseDrawerUI");
        _houseDrawerUIOriginal(a1);
        EndPerfLog("HouseDrawerUI");
    }

    [UnmanagedCallersOnly]
    private static void RagdollHook(nint a1)
    {
        StartPerfLog("Ragdoll");
        _ragdollOriginal(a1);
        EndPerfLog("Ragdoll");
    }

    [UnmanagedCallersOnly]
    private static void FurnitureBuildingUIHook(nint a1)
    {
        StartPerfLog("FurnitureBuildingUI");
        _furnitureBuildingUIOriginal(a1);
        EndPerfLog("FurnitureBuildingUI");
    }

    [UnmanagedCallersOnly]
    private static void FurnitureClickHandlerHook(nint a1)
    {
        StartPerfLog("FurnitureClickHandler");
        _furnitureClickHandlerOriginal(a1);
        EndPerfLog("FurnitureClickHandler");
    }

    [UnmanagedCallersOnly]
    private static void ButchBoxHook(nint a1)
    {
        StartPerfLog("ButchBox");
        _butchBoxOriginal(a1);
        EndPerfLog("ButchBox");
    }

    [UnmanagedCallersOnly]
    private static void CatStatsDrawerHook(nint a1)
    {
        StartPerfLog("CatStatsDrawer");
        _catStatsDrawerOriginal(a1);
        EndPerfLog("CatStatsDrawer");
    }

    [UnmanagedCallersOnly]
    private static void FurnitureGridHook(nint a1)
    {
        StartPerfLog("FurnitureGrid");
        _furnitureGridOriginal(a1);
        EndPerfLog("FurnitureGrid");
    }

    [UnmanagedCallersOnly]
    private static void FurniturePieceHook(nint a1)
    {
        StartPerfLog("FurniturePiece");
        _furniturePieceOriginal(a1);
        EndPerfLog("FurniturePiece");
    }

    [UnmanagedCallersOnly]
    private static void HouseHook(nint a1)
    {
        StartPerfLog("House");
        _houseOriginal(a1);
        EndPerfLog("House");
    }

    [UnmanagedCallersOnly]
    private static void HouseCatHook(nint a1)
    {
        StartPerfLog("HouseCat");
        _houseCatOriginal(a1);
        EndPerfLog("HouseCat");
    }

    [UnmanagedCallersOnly]
    private static void HouseCatClickManagerHook(nint a1)
    {
        StartPerfLog("HouseCatClickManager");
        _houseCatClickManagerOriginal(a1);
        EndPerfLog("HouseCatClickManager");
    }

    [UnmanagedCallersOnly]
    private static void HouseCatPhysicsHook(nint a1)
    {
        StartPerfLog("HouseCatPhysics");
        _houseCatPhysicsOriginal(a1);
        EndPerfLog("HouseCatPhysics");
    }

    [UnmanagedCallersOnly]
    private static void HousePipeHook(nint a1)
    {
        StartPerfLog("HousePipe");
        _housePipeOriginal(a1);
        EndPerfLog("HousePipe");
    }

    [UnmanagedCallersOnly]
    private static void HouseTutorialDriverHook(nint a1)
    {
        StartPerfLog("HouseTutorialDriver");
        _houseTutorialDriverOriginal(a1);
        EndPerfLog("HouseTutorialDriver");
    }

    [UnmanagedCallersOnly]
    private static void InventoryTrashDrawersHook()
    {
        StartPerfLog("InventoryTrashDrawers");
        _inventoryTrashDrawersOriginal();
        EndPerfLog("InventoryTrashDrawers");
    }

    [UnmanagedCallersOnly]
    private static void NPCMapDrawerHook(nint a1)
    {
        StartPerfLog("NPCMapDrawer");
        _nPCMapDrawerOriginal(a1);
        EndPerfLog("NPCMapDrawer");
    }

    [UnmanagedCallersOnly]
    private static void SingingCatHook(nint a1)
    {
        StartPerfLog("SingingCat");
        _singingCatOriginal(a1);
        EndPerfLog("SingingCat");
    }

    [UnmanagedCallersOnly]
    private static void ButtonHook(nint a1)
    {
        StartPerfLog("Button");
        _buttonOriginal(a1);
        EndPerfLog("Button");
    }

    [UnmanagedCallersOnly]
    private static void AbilityTooltipHook(nint a1)
    {
        StartPerfLog("AbilityTooltip");
        _abilityTooltipOriginal(a1);
        EndPerfLog("AbilityTooltip");
    }

    [UnmanagedCallersOnly]
    private static void AABBTreeBroadphaseHook(nint a1)
    {
        StartPerfLog("AABBTreeBroadphase");
        _aABBTreeBroadphaseOriginal(a1);
        EndPerfLog("AABBTreeBroadphase");
    }

    [UnmanagedCallersOnly]
    private static void AudioSourceHook(nint a1)
    {
        StartPerfLog("AudioSource");
        _audioSourceOriginal(a1);
        EndPerfLog("AudioSource");
    }

    [UnmanagedCallersOnly]
    private static void AnimationAudioEventsHook(nint a1)
    {
        StartPerfLog("AnimationAudioEvents");
        _animationAudioEventsOriginal(a1);
        EndPerfLog("AnimationAudioEvents");
    }

    [UnmanagedCallersOnly]
    private static void CatRagdollHook(nint a1)
    {
        StartPerfLog("CatRagdoll");
        _catRagdollOriginal(a1);
        EndPerfLog("CatRagdoll");
    }

    [UnmanagedCallersOnly]
    private static void CombatCatVoice_EmotionsHook(nint a1)
    {
        StartPerfLog("CombatCatVoice_Emotions");
        _combatCatVoice_EmotionsOriginal(a1);
        EndPerfLog("CombatCatVoice_Emotions");
    }

    [UnmanagedCallersOnly]
    private static void FurnitureGridIconsHook(nint a1)
    {
        StartPerfLog("FurnitureGridIcons");
        _furnitureGridIconsOriginal(a1);
        EndPerfLog("FurnitureGridIcons");
    }

    [UnmanagedCallersOnly]
    private static void FurnitureMenuButtonHook(nint a1)
    {
        StartPerfLog("FurnitureMenuButton");
        _furnitureMenuButtonOriginal(a1);
        EndPerfLog("FurnitureMenuButton");
    }

    [UnmanagedCallersOnly]
    private static void HouseDrawerPanelHook(nint a1)
    {
        StartPerfLog("HouseDrawerPanel");
        _houseDrawerPanelOriginal(a1);
        EndPerfLog("HouseDrawerPanel");
    }

    [UnmanagedCallersOnly]
    private static void HouseTestHook(nint a1)
    {
        StartPerfLog("HouseTest");
        _houseTestOriginal(a1);
        EndPerfLog("HouseTest");
    }

    [UnmanagedCallersOnly]
    private static void TrashScreenItemBox2Hook(nint a1)
    {
        StartPerfLog("TrashScreenItemBox2");
        _trashScreenItemBox2Original(a1);
        EndPerfLog("TrashScreenItemBox2");
    }

    [UnmanagedCallersOnly]
    private static void ButtonManagerHook(nint a1)
    {
        StartPerfLog("ButtonManager");
        _buttonManagerOriginal(a1);
        EndPerfLog("ButtonManager");
    }
}